### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'phantom.args.length')

### ISSUE THREAD

**Issue by cebindani** [founddrama/phantomjs-cookbook#1]
I'm getting an error when I try to run the *recipe04.js* using following the book's steps 
 >_phantomjs chapter01/recipe04.js foo bar "boo baa"_

`TypeError: undefined is not an object (evaluating 'phantom.args.length')`
`  phantomjs://code/recipe04.js:7 in global code`

I'm using phantomjs version 2.1.1

**Comment by cebindani** [comment]
I fixed it, but I have no permission to add a pull request here.

**Comment by founddrama** [comment]
@cebindani Thanks for your interest in the project! If you look at the sample code in the broader context though, it goes along with the [PhantomJS Cookbook](https://www.packtpub.com/web-development/phantomjs-cookbook) which does specifically target the 1.9.x versions. The fact that `phantom.args` was a deprecated part of the API is specifically discussed in the text.

I haven't been approached about a revised version for 2.0, and have no plans at this time to write one.
